######################################################################
# Automatically generated by qmake (3.1) Sun Dec 15 20:17:29 2024
######################################################################

TEMPLATE = app
TARGET = neoada
INCLUDEPATH += .
QT -= widgets
CONFIG += debug

NEOADA_PATH = ../libneoada
include(../libneoada/libneoada.pro)

# Input
SOURCES += main.cc
